name: Build

on:
  schedule:
    - cron: "5 1 * * *"
  push:
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set execute permissions for compile.sh
        run: chmod +x ./compile.sh

      - name: Compile LaTeX document (Vietnamese)
        uses: xu-cheng/texlive-action@v2
        with:
          texlive_version: 2024
          run: |
            export LC_ALL=C.UTF-8
            ./compile.sh

      - name: Upload Vietnamese PDF as Artifact
        if: github.ref != 'refs/heads/master' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: document.pdf
          path:
            document.pdf

      # Configure Git to commit PDF file
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Commit and push PDF to the repository
      - name: Commit and Push PDF to Repository
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          git add document.pdf
          git commit -m "Add compiled PDF document"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload PDF File to Release
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.pdf"
          tags: false
          overwrite: true
          draft: false
          update_latest_release: true
